# CS236605: Deep Learning

# Tutorial 1: Python, numpy and friends 🐍

## Introduction

Python is a great general-purpose programming language on its own and with the addition of a few
popular libraries such as `numpy`, `pandas`, `scikit-learn`, `matplotlib` and others it becomes an
effective scientific computing environment.

Recently many Deep Learning frameworks have emerged for python.
Arguably the most notable ones in 2019 are TensorFlow (with the Keras frontend) and PyTorch.
In this course we'll use PyTorch, which is gaining traction as the leading DL framework for research.

Many of you may have some experience with Python and numpy; for the rest of you, this section will serve as a quick crash course both on the Python programming language and on the use of Python for scientific computing.

If you have previous knowledge in Matlab,
we recommend the [numpy for Matlab users](https://docs.scipy.org/doc/numpy-1.15.0/user/numpy-for-matlab-users.html) page as a useful resource.

In this tutorial, we will cover:

* Environment setup with `conda`
* Jupyter: Creating notebooks, workflows
* Basic Python: Basic data types (Containers, Lists, Dictionaries, Sets, Tuples), Functions, Classes
* Numpy: Arrays, Array indexing, Datatypes, Array math, Broadcasting

Credit: Some parts of this tutorial were adapted from the [CS231n Python tutorial](http://cs231n.github.io/python-numpy-tutorial/) by Justin Johnson.

## Environment setup

To install and manage all the necessary packages and dependencies for the
course tutorials and assignments, we use [conda](https://conda.io), a popular package-manager for python.

- The tutorial notebooks come with an `environment.yml` file which defines which third-party libraries we depend on.
- Conda will use this file to create a virtual environment for you.
- This virtual environment includes python and all other packages and tools we specified, separated from any preexisting
python installation you may have.

### Installation

Install the python3 version of [miniconda](https://conda.io/miniconda.html).
Follow the [installation instructions](https://conda.io/docs/user-guide/install/index.html)
for your platform.

Install all dependencies with `conda`:

```shell
conda env update -f environment.yml
```

To activate the virtual environment (set up `$PATH`):

```shell
conda activate cs236605-tutorials
```

To check what conda environments you have and which is active, run

```shell
conda env list
```

### Running Jupyter

From a terminal, enter the folder contaning the tutorial notebooks.
Make sure that the active conda environment is `cs236605-tutorials`, and run

```shell
jupyter lab
```

This will start a [jupyter lab](https://jupyterlab.readthedocs.io/en/stable/)
server and open your browser at the local server's url. You can now start working with the notebooks.

If you're new to jupyter notebooks, you can get started by reading the
[UI guide](https://jupyter-notebook.readthedocs.io/en/stable/notebook.html#notebook-user-interface)
and also about how to use notebooks in
[JupyterLab](https://jupyterlab.readthedocs.io/en/latest/user/notebook.html).


#### Jupyter basics

Jupyter notebooks consist mainly of code and markdown cells.
The code cells contain code that is run by a `kernel`, an
interpreter for some programming language, python in our case.

In [1]:
# This is a code cell
def the_answer():
    return 42

the_answer()

42

This is a markdown cell. You can use markdown syntax to format your text, and also include equations
written in $\LaTeX$:

$$
e^{i\pi} - 1 = 0
$$

Other useful things to know about:
* Opening a console for notebook
* Restarting kernel
* Magics

In [2]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## Basics of Python

Python is a high-level, dynamically typed multiparadigm programming language. Python code is often said to be almost like pseudocode, since it allows you to express very powerful ideas in very few lines of code while being very readable. As an example, here is an implementation of the classic quicksort algorithm in Python:

In [3]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

print(quicksort([3,6,8,10,1,2,1]))

[1, 1, 2, 3, 6, 8, 10]


Python has great [documentation](https://docs.python.org/3)! Use it often.

### Packages and modules

A python **module** is simply a python file (`.py`), which can contain functions, classes and even top-level code.

A **package** is a collection of modules within a directory. Python comes with a standard library which
includes many useful packages.

A package must be imported before use. They can be imported like so:

In [4]:
# Import packages from the python standard library
import math
import sys

Additionally, we can define our own packages and modules. This tutorial comes with a `demo_package`
which includes a `demo_module`.

Any object can be imported from a module like so:

In [5]:
# Import just a specific function from a specific module from a specific package
from demo_package.demo_module import demo_func

demo_func(math.pi)
print('FOO', file=sys.stdout)

this is a demo, a=17
this is a demo, a=3.141592653589793
FOO


### Basic data types

#### Numbers

Integers and floats work as you would expect from other languages:

In [6]:
x = 3
print(x, type(x))

3 <class 'int'>


In [7]:
print(x + 1)  # Addition;
print(x - 1)  # Subtraction;
print(x * 2)  # Multiplication;
print(x ** 2)  # Exponentiation;

4
2
6
9


In [8]:
x += 1
print(x)
x *= 2
print(x)

4
8


In [9]:
y = 2.5
print(type(y))
print(y, y + 1, y * 2, y ** 2, y / 2, y // 2)

<class 'float'>
2.5 3.5 5.0 6.25 1.25 1.0


Note that unlike many languages, Python does not have unary increment (x++) or decrement (x--) operators.

Python also has built-in types for long integers and complex numbers; you can find all of the details in the [documentation](https://docs.python.org/3/library/stdtypes.html#numeric-types-int-float-long-complex).

#### Booleans

Python implements all of the usual operators for Boolean logic, but uses English words rather than symbols (`&&`, `||`, etc.):

In [10]:
t, f = True, False

Now we let's look at the operations:

In [11]:
print(t and f) # Logical AND
print(t or f ) # Logical OR
print(not t  ) # Logical NOT
print(t != f ) # Logical XOR

False
True
False
True


#### Strings

In [12]:
hello = 'hello'   # String literals can use single quotes
world = "world"   # or double quotes; it does not matter.
hello, len(hello)

('hello', 5)

In [13]:
# String concatenation
'aaa ' + 'bbb'

'aaa bbb'

There are several way to created formatted strings, here are a couple:

In [14]:
s = 'hello'
a = [1,2,3]

# sprintf style string formatting
print('%s %s: pi=%.5f' % (s, a, math.pi))

# formatting with f-string literals (python 3.6+)
print(f'{s} {a}: pi={math.pi:.5f}')

hello [1, 2, 3]: pi=3.14159
hello [1, 2, 3]: pi=3.14159


String objects have a bunch of useful methods; for example:

In [15]:
s = "hello"
print(s.capitalize() ) # Capitalize a string; prints "Hello"
print(s.upper()      ) # Convert a string to uppercase; prints "HELLO"
print(s.rjust(7)     ) # Right-justify a string, padding with spaces; prints "  hello"
print(s.center(7)    ) # Center a string, padding with spaces; prints " hello "
print(s.replace('l', '(ell)'))  # Replace all instances of one substring with another
print('  world '.strip())  # Strip leading and trailing whitespace; prints "world"

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


You can find a list of all string methods in the [documentation](https://docs.python.org/3/library/stdtypes.html#string-methods).

### Containers

Python includes several built-in container types: lists, dictionaries, sets, and tuples.

#### Lists

A list is the Python equivalent of an array, but is resizeable and can contain elements of different types:

In [16]:
xs = [3, 1, 2]   # Create a list
print(xs)
print(xs[2], xs[-1]) # Negative indices count from the end of the list; prints "2"

[3, 1, 2]
2 2


In [17]:
xs[2] = 'foo'    # Lists can contain elements of different types
print(xs)

[3, 1, 'foo']


In [18]:
xs.append('bar') # Add a new element to the end of the list
print(xs)

[3, 1, 'foo', 'bar']


In [19]:
x = xs.pop()     # Remove and return the last element of the list
x, xs

('bar', [3, 1, 'foo'])

#### Slicing

In addition to accessing list elements one at a time, Python provides concise syntax to access sublists; this is known as slicing:

In [20]:
nums = list(range(5))
nums

[0, 1, 2, 3, 4]

In [21]:
nums[2:4]    # Get a slice from index 2 to 4 (exclusive)

[2, 3]

In [22]:
nums[2:]     # Get a slice from index 2 to the end

[2, 3, 4]

In [23]:
nums[:2]     # Get a slice from the start to index 2 (exclusive)

[0, 1]

In [24]:
nums[:]      # Get a slice of the whole list

[0, 1, 2, 3, 4]

In [25]:
nums[:-1]    # Slice indices can be negative

[0, 1, 2, 3]

In [26]:
nums[0:4:2]  # Can also specify slice step size

[0, 2]

In [27]:
nums[2:4] = [8, 9] # Assign a new sublist to a slice
nums

[0, 1, 8, 9, 4]

In [28]:
# Delete elements from a list
nums[0:1] = []
del nums[-1]
nums

[1, 8, 9]

#### Loops

You can loop over the elements of a list like this:

In [29]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)

cat
dog
monkey


If you want access to the index of each element within the body of a loop, use the built-in `enumerate` function:

In [30]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print(f'#{idx+1}: {animal}')

#1: cat
#2: dog
#3: monkey


#### List comprehensions

When programming, frequently we want to transform one type of data into another. As a simple example, consider the following code that computes square numbers:

In [31]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
squares

[0, 1, 4, 9, 16]

You can make this code simpler using a list comprehension:

In [32]:
squares = [x ** 2 for x in nums]
squares

[0, 1, 4, 9, 16]

List comprehensions can also contain conditions:

In [33]:
even_squares = [x ** 2 for x in nums if x % 2 == 0]
even_squares

[0, 4, 16]

List comprehensions can be nested:

In [34]:
nums2 = [-1, 1]
[x * y for x in nums for y in nums2]

[0, 0, -1, 1, -2, 2, -3, 3, -4, 4]

#### Dictionaries

A dictionary stores (key, value) pairs. In other languages this is known as a `Map` or `Hash`.

In [35]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(d['cat'])       # Get an entry from a dictionary
print('cat' in d)     # Check if a dictionary has a given key

cute
True


In [36]:
d['fish'] = 'wet'    # Set an entry in a dictionary
d

{'cat': 'cute', 'dog': 'furry', 'fish': 'wet'}

In [37]:
# Trying to access a non-existing key raises a KeyError
try:
    d['monkey']
except KeyError as e:
    print(e, file=sys.stderr)

'monkey'


In [38]:
print(d.get('monkey', 'N/A'))  # Get an element with a default
print(d.get('fish', 'N/A'))    # Get an element with a default

N/A
wet


In [39]:
del d['fish']        # Remove an element from a dictionary
d

{'cat': 'cute', 'dog': 'furry'}

In [40]:
# Iteration over keys
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    print(f'A {animal} has {d[animal]} legs')

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


In [41]:
# Iterate over key-value pairs
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, num_legs in d.items():
    print(f'A {animal} has {num_legs} legs')

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


In [42]:
# Create a dictionary using the built-in dict() function
dict(foo=1, bar=2, baz=3)

{'foo': 1, 'bar': 2, 'baz': 3}

#### Dictionary comprehensions

These are similar to list comprehensions, but allow you to easily construct dictionaries. For example:

In [43]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
even_num_to_square

{0: 0, 2: 4, 4: 16}

#### Sets

A set is an unordered collection of distinct elements

In [44]:
animals = {'cat', 'dog'}
print(animals)
print('cat' in animals )  # Check if an element is in a set
print('fish' in animals) # prints "False"

{'cat', 'dog'}
True
False


In [45]:
animals.add('fish') # Add an element to a set
print('fish' in animals)
len(animals) # Number of elements in a set

True


3

In [46]:
animals.add('cat')       # Adding an element that is already in the set does nothing
animals

{'cat', 'dog', 'fish'}

_Loops_: Iterating over a set has the same syntax as iterating over a list; however since sets are unordered, you cannot make assumptions about the order in which you visit the elements of the set:

In [47]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print(f'#{idx}: {animal}')

#0: cat
#1: dog
#2: fish


#### Set comprehensions

Like lists and dictionaries, we can easily construct sets using set comprehensions:

In [48]:
from math import sqrt
s = {int(sqrt(x)) for x in range(37)}
s

{0, 1, 2, 3, 4, 5, 6}

#### Tuples

A tuple is an **immutable** ordered list of values.

In [49]:
t = (1, 2, 'three')
t

(1, 2, 'three')

It can be used in ways similar to a list:

In [50]:
t[0:1], t[1:3], t[-1], len(t)

((1,), (2, 'three'), 'three', 3)

A tuple can be used a key in a dictionary and as an element of a sets, while **lists cannot**.

In [51]:
d = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
d

{(0, 1): 0,
 (1, 2): 1,
 (2, 3): 2,
 (3, 4): 3,
 (4, 5): 4,
 (5, 6): 5,
 (6, 7): 6,
 (7, 8): 7,
 (8, 9): 8,
 (9, 10): 9}

A tuple (and also a list) can be **unpacked**:

In [52]:
one, two, three = t
one, two, three

(1, 2, 'three')

Note that when retuning multiple values from a function (or code block in a jupyter notebook, as above)
your values get wrapped in a tuple, and the tuple is what's returned.
Unpacking the return value of a function can make it seem as if multiple values were returned.

### Functions

Python functions are defined using the `def` keyword. For example:

In [53]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))

negative
zero
positive


We will often define functions to take optional keyword arguments, like this:

In [54]:
def hello(name, loud=False):
    if loud:
        print('HELLO, %s' % name.upper())
    else:
        print('Hello, %s!' % name)

hello('Bob')
hello('Fred', loud=True)

Hello, Bob!
HELLO, FRED


#### Positional and Keyword arguments

Python functions are very flexible in the way they accept arguments. Both positional (regular) and keyword
arguments are supported and can be mixed in the same definition. Additionally, extra arguments can be passed in with the `*args` and `**kwargs` constructs.

Here's a function with three positional arguments and three keyword arguments which also accepts extra 
positional and keyword arguments.

In [55]:
def myfunc(a1, a2, a3, *extra_args, kw1='foo', kw2='bar', kw3=3, **extra_kwargs):
    print(f'Got positional args: {(a1, a2, a3)}')
    print(f'Got keyword args   : {dict(kw1=kw1, kw2=kw3, kw3=kw3)}')
    print(f'Got extra positional args: {extra_args}')
    print(f'Got extra keyword args: {extra_kwargs}')

It can be called in many ways:

In [56]:
myfunc(1,2,3,4,5,6)

Got positional args: (1, 2, 3)
Got keyword args   : {'kw1': 'foo', 'kw2': 3, 'kw3': 3}
Got extra positional args: (4, 5, 6)
Got extra keyword args: {}


In [57]:
my_args = [1,2,3,4]
myfunc(*my_args)

Got positional args: (1, 2, 3)
Got keyword args   : {'kw1': 'foo', 'kw2': 3, 'kw3': 3}
Got extra positional args: (4,)
Got extra keyword args: {}


In [58]:
myfunc(1,2,3, kw3=3, kw2=2, foo='bar')

Got positional args: (1, 2, 3)
Got keyword args   : {'kw1': 'foo', 'kw2': 3, 'kw3': 3}
Got extra positional args: ()
Got extra keyword args: {'foo': 'bar'}


In [59]:
my_kwargs = dict(kw1=1, kw2=2, kw3=3, kw4=4)
myfunc(1,2,3, **my_kwargs)

Got positional args: (1, 2, 3)
Got keyword args   : {'kw1': 1, 'kw2': 3, 'kw3': 3}
Got extra positional args: ()
Got extra keyword args: {'kw4': 4}


Note that keyword args can be omitted, while positional args cannot:

In [60]:
try:
    myfunc(1,2)
except TypeError as e:
    print(e, file=sys.stderr)

myfunc() missing 1 required positional argument: 'a3'


### Classes

The syntax for defining classes in Python is straightforward:

In [61]:
class Greeter:

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
            print('HELLO, %s!' % self.name.upper())
        else:
            print('Hello, %s' % self.name)

g = Greeter('Fred')  # Construct an instance of the Greeter class
g.greet()            # Call an instance method
g.greet(loud=True)   # Call an instance method

Hello, Fred
HELLO, FRED!


Classes can implement special **magic functions** that enable them to be integrated nicely with other python code. Magic functions have special names that start and end with `__`.

For example, here's a class that can be indexed with `[]` and iterated over with a `for` loop.

In [62]:
class ExampleCollection(object):
    def __init__(self):
        self.items = [100, 200, 300]
    
    def __len__(self):
        return len(self.items)
    
    def __getitem__(self, idx):
        return self.items[idx]
    
    def __iter__(self):
        class ExampleIter():
            def __init__(self, collection):
                self.idx = 0
                self.collection = collection
                
            def __next__(self):
                if self.idx >= len(self.collection):
                    raise StopIteration()
                x = self.collection[self.idx]
                self.idx += 1
                return x
                
        return ExampleIter(self)
    

In [63]:
example = ExampleCollection()
print('length=', len(example)) # invokes __len__
print('example[0]=', example[0]) # invokes __getitem__

length= 3
example[0]= 100


In [64]:
for x in example: # invokes __iter__ and it's __next__
    print(x)

100
200
300


Many other magic functions exist. Consult the docs and see if you can catch 'em all!

## Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

To use Numpy, we first need to import the `numpy` package:

In [65]:
import numpy as np

### Arrays

A numpy array represents an n-dimentional grid of values, all of the same type, and is indexed by a tuple of nonnegative integers.

- The number of dimensions is the **rank** of the array
- The **shape** of an array is a tuple of integers giving the size of the array along each dimension

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [66]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print(f'type={type(a)}, shape={a.shape}, a[1]={a[1]}')

type=<class 'numpy.ndarray'>, shape=(3,), a[1]=2


In [67]:
a[0] = 5                 # Change an element of the array
a

array([5, 2, 3])

In [68]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b)
print('shape =', b.shape)

[[1 2 3]
 [4 5 6]]
shape = (2, 3)


In [69]:
b[0, 0], b[0, 1], b[1, 0]

(1, 2, 4)

Numpy also provides many functions to create arrays:

In [70]:
np.zeros((2,2))  # Create an array of all zeros

array([[0., 0.],
       [0., 0.]])

In [71]:
np.ones((1,10))   # Create an array of all ones

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [72]:
np.full((3,3), 7.2) # Create a constant array

array([[7.2, 7.2, 7.2],
       [7.2, 7.2, 7.2],
       [7.2, 7.2, 7.2]])

In [73]:
np.eye(4, dtype=np.int) # Create an identity matrix of integers

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [74]:
t = np.random.random((4,4,3)) # Create a 3d-array filled with random values
t

array([[[0.85287444, 0.32993568, 0.2131981 ],
        [0.07162191, 0.78601752, 0.05206168],
        [0.33450874, 0.06885908, 0.91387323],
        [0.96104138, 0.0507156 , 0.37605353]],

       [[0.26820963, 0.99672158, 0.34661314],
        [0.71167916, 0.85158872, 0.5433284 ],
        [0.06079206, 0.69403511, 0.9783253 ],
        [0.66974117, 0.80177025, 0.661506  ]],

       [[0.52452475, 0.2125442 , 0.2493527 ],
        [0.89279346, 0.38766587, 0.21459703],
        [0.38485174, 0.82027643, 0.16231713],
        [0.35619065, 0.90309695, 0.28191285]],

       [[0.63227666, 0.18723994, 0.58705817],
        [0.50418652, 0.96685555, 0.37620633],
        [0.57719163, 0.53105585, 0.87834943],
        [0.81307986, 0.86608449, 0.28938083]]])

In [75]:
t[1,1,2]

0.5433284037085563

#### Rank-1 Arrays

In `numpy` **rank-1** arrays of length `n` have a shape of `(n,)`. Such arrays are somewhat special in that `numpy` can treat them both as column or as row vectors.



In [76]:
# A rank-1 array
a1 = np.array([1,2,3])
print(f'a1 {a1.shape}:\n', a1)

a1 (3,):
 [1 2 3]


In [77]:
# A columns vector (1 column and "-1" rows means "figure it out")
a_col = a1.reshape(-1, 1)
print(f'a_col {a_col.shape}:\n', a_col)

a_col (3, 1):
 [[1]
 [2]
 [3]]


In [78]:
# A row vector (1 row and "-1" columns)
a_row = a1.reshape(1, -1)
print(f'a_row {a_row.shape}=\n', a_row)

a_row (1, 3)=
 [[1 2 3]]


Rank-1 arrays have different semantics when using them in vector-vector or vector-matrix products, so always make sure you known what shapes you're working with:

In [79]:
print('a1 * a1 =', np.dot(a1, a1))

print('a_row * a1 =', np.dot(a_row, a1))

print('a1 * a_col =', np.dot(a1, a_col))

print('a_row * a_col =', np.dot(a_row, a_col))
print('a_col * a_row =\n', np.dot(a_col, a_row))

a1 * a1 = 14
a_row * a1 = [14]
a1 * a_col = [14]
a_row * a_col = [[14]]
a_col * a_row =
 [[1 2 3]
 [2 4 6]
 [3 6 9]]


### Array indexing

Numpy offers several ways to index into arrays.

**Slicing**

Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify **a slice for each dimension** of the array:

In [80]:
import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [81]:
b = a[:2, 1:3]
b

array([[2, 3],
       [6, 7]])

A slice of an array is a **view** into the same in-memory data, so modifying it will modify the original array.

In [82]:
b[0, 0] = 77777
a

array([[    1, 77777,     3,     4],
       [    5,     6,     7,     8],
       [    9,    10,    11,    12]])

You can also mix integer indexing with slice indexing.
However, doing so will yield an array of **lower rank** than the original array.

Note that this is quite different from the way that MATLAB handles array slicing.

In [83]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Two ways of accessing the data in the middle row of the array.
Mixing integer indexing with slices yields an array of lower rank,
while using only slices yields an array of the same rank as the
original array:

In [84]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a

print(row_r1, 'shape=', row_r1.shape)
print(row_r2, 'shape=', row_r2.shape)
print(row_r3, 'shape=', row_r3.shape)

[5 6 7 8] shape= (4,)
[[5 6 7 8]] shape= (1, 4)
[[5 6 7 8]] shape= (1, 4)


In [85]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]

print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


**Integer array indexing** 

- When you slice, the resulting array view will always be a subarray of the original array.
- Integer array indexing allows you to construct arbitrary arrays using the data from another array.


In [86]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [87]:
# An example of integer array indexing.
# The returned array will have shape (3,)
print(a[[0, 1, 2], [0, 1, 0]])

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]
[1 4 5]


In [88]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))

[2 2]
[2 2]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [89]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [90]:
# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
a[np.arange(4), b]

array([ 1,  6,  7, 11])

In [91]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 1000
a

array([[1001,    2,    3],
       [   4,    5, 1006],
       [1007,    8,    9],
       [  10, 1011,   12]])

**Boolean array indexing**

This type of indexing is used to select the elements of an array that satisfy some condition
(similar to MATLAB's logical indexing).

In [92]:
a = np.array([[1,2], [3, 4], [5, 6]])
print('a=\n', repr(a))
bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

bool_idx

a=
 array([[1, 2],
       [3, 4],
       [5, 6]])


array([[False, False],
       [ True,  True],
       [ True,  True]])

In [93]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
a[a>2]

array([3, 4, 5, 6])

For brevity we have left out a lot of details about numpy array indexing; if you want to know more you should read the [documentation](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html).

### Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [94]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

x.dtype, y.dtype, z.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

### Array math

#### Elementwise operations
Basic mathematical functions **operate elementwise** on arrays, and are available both as operator overloads and as functions in the numpy module:

In [95]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [96]:
# Elementwise difference
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [97]:
# Elementwise product
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [98]:
# Elementwise division
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [99]:
# Elementwise square root
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


There are of course many more elementwise operations inmplemented by `numpy`.

#### Inner products

Unlike MATLAB, `*` is elementwise multiplication, not matrix multiplication (as we say above).

We instead use the `dot()` function to:
- compute inner products of vectors,
- multiply a vector by a matrix, and to
- multiply matrices.

The `dot()` function is available both as a function in the numpy module and as an instance
method of array objects.

In [100]:
v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

219
219


In [101]:
x = np.array([[1,2],[3,4]])
print('x=\n', repr(x))

# Matrix-vector product; produce a rank 1 array
print('x dot v=', x.dot(v))

x=
 array([[1, 2],
       [3, 4]])
x dot v= [29 67]


In [102]:
# Matrix-matrix product; produces a rank 2 array
y = np.array([[5,6],[7,8]])
print('y=\n', repr(y))

print('x dot y =\n', x.dot(y))

y=
 array([[5, 6],
       [7, 8]])
x dot y =
 [[19 22]
 [43 50]]


Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [103]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements
print(np.sum(x, axis=0))  # Compute sum of each column
print(np.sum(x, axis=1) ) # Compute sum of each row

10
[4 6]
[3 7]


You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to **reshape** or otherwise manipulate data in arrays.

In [104]:
# Transpose
print(x)
print(x.T)
print(np.transpose(x))

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


In [105]:
v = np.array([1,2,3]) # rank 1
print(v.reshape(1, -1)) # row vector
print(v.reshape(-1, 1)) # column vector

[[1 2 3]]
[[1]
 [2]
 [3]]


### Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of **different shapes** when performing arithmetic operations.

Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [106]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

print('x=', x)
print('v=', v)

x= [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
v= [1 0 1]


In [107]:
# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

This works; however when the matrix `x` is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix `x` is equivalent to forming a matrix `vv` by stacking multiple copies of `v` vertically, then performing elementwise summation of `x` and `vv`. We could implement this approach like this:

In [108]:
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
vv

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1]])

In [109]:
y = x + vv  # Add x and vv elementwise
y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [110]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting

print('shapes: ', x.shape, v.shape)
y

shapes:  (4, 3) (3,)


array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

The line `y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting; this line works as if v actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

1. All input arrays with ndim smaller than the input array of largest ndim, have 1’s prepended to their shapes.
1. The size in each dimension of the output shape is the maximum of all the input sizes in that dimension.
1. An input can be used in the calculation if its size in a particular dimension either matches the output size in that dimension, or has value exactly 1.
1. If an input has a dimension size of 1 in its shape, the first data entry in that dimension will be used for all calculations along that dimension. In other words, the stepping machinery of the ufunc will simply not step along that dimension (the stride will be 0 for that dimension).


If this explanation does not make sense, try reading the explanation from the [documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) or this [explanation](http://wiki.scipy.org/EricsBroadcastingDoc).

Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the [documentation](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

Here are some applications of broadcasting:

In [111]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)

# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
np.reshape(v, (3, 1)) * w

array([[ 4,  5],
       [ 8, 10],
       [12, 15]])

In [112]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
x * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the [numpy reference](http://docs.scipy.org/doc/numpy/reference/) to find out much more about numpy.

## PyTorch Tensors

In [113]:
import torch
torch.__version__

'1.0.1.post2'

PyTorch is a relatively new yet widely used deep learning framework.
During the course we'll use it extensively and learn many parts of this API.
This notebook will show a small part of PyTorch's API, the `Tensor` class.
This class provides is a GPU-enabled replacement for numpy's `ndarray`.

This notebook will show some brief examples, just to get a feel for it and compare it to the usual numpy `ndarray`s.
You will be using both PyTorch tensors and numpy `ndarray`s extensively throughout the course homework assignments.

In [114]:
# Basic tensor creation
t = torch.tensor([[1, 2, 3], [4, 5, 6]])
t

tensor([[1, 2, 3],
        [4, 5, 6]])

Some other tensor construction methods:

In [115]:
torch.zeros((1,2))

tensor([[0., 0.]])

In [116]:
torch.ones((3,2))

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [117]:
torch.randint(10, (4,1))

tensor([[3],
        [4],
        [7],
        [3]])

As in numpy, tensors can be reshaped

In [118]:
t.reshape(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In many cases, PyTorch provides the same methods on both the `Tensor` object and via the `torch` package.

In [119]:
torch.reshape(t, (3, -1))

tensor([[1, 2],
        [3, 4],
        [5, 6]])

Properties of a tensor:

In [120]:
print('shape:', t.size())   # t.shape also works, like numpy
print('dimensions:', t.dim())
print('type:', t.type())

shape: torch.Size([2, 3])
dimensions: 2
type: torch.LongTensor


**Slicing** works just like in numpy:

In [121]:
t = torch.Tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
t

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [122]:
t[:, -1]

tensor([3., 6., 9.])

In [123]:
t[:2, :]

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [124]:
t[-1:, -1:]

tensor([[9.]])

Unlike numpy, PyTorch tensors can be moved to **GPU** memory (if a GPU is available on the machine).

In [125]:
if torch.cuda.is_available():
    t = t.cuda()

In [126]:
# Better way to use GPU tensors (and later - models)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
t = t.to(device)

**Broadcasting** also works (with almost identical semantics):

In [127]:
x = torch.tensor([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = torch.tensor([1, 0, 1])
print('shapes: ', x.shape, v.shape)
print(x)
print(v)

shapes:  torch.Size([4, 3]) torch.Size([3])
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
tensor([1, 0, 1])


In [128]:
y = x + v  # Add v to each row of x using broadcasting
y

tensor([[ 2,  2,  4],
        [ 5,  5,  7],
        [ 8,  8, 10],
        [11, 11, 13]])